version: '3.8'

services:
    db:
        image: 'postgres:12'
        environment:
          - POSTGRES_DB=db
          - POSTGRES_USER=Gandalf
          - POSTGRES_PASSWORD=Middle Earth
        ports:
          - '5432:5432'  